### ISSUE TITLE
Unique target_id for each planet?

### ISSUE THREAD

**Issue by gjgilbert** [ExoJulia/ExoplanetsSysSim.jl#6]
Hi Matthias & Eric,

I'm doing a little work comparing observed and simulated catalogues, and I'm finding that it would be helpful to have a unique ID for each planet, akin to KOIs, i.e. "40.1, 40.2, etc." for planets in the same system.

Right now the target_id column appears to be redundant with the star_id column, and because the periods in the observed and physical catalogues are slightly different (presumably due to subtle effect of modeling the observations), it's a bit tricky to pull out the "undetected" planets for comparison.

FYI, I'm running the same version of SysSim/ExoJulia as when we last chatted on Oct 17.

There's nothing urgent about this issue - just a small suggestion to improve usability for future updates.

Thanks!
Greg

**Comment by hematthi** [comment]
Hi Greg,

Thanks, I'll keep that in mind. I agree that it's a little hard match the planets in the observed catalog with the planets in the physical catalog since the periods are slightly different (and you're  right, due to modeling observations), so it's hard to determine which planets in the physical catalog are undetected. One idea is to just find the _closest_ period to the observed one, which I imagine would work almost always.
Also, we actually do have a field recording an "id" for each planet (see the file "src/planet.jl" in this repo), but we have been using it to record the "cluster id" of each planet for the purposes of tracking/counting clusters instead of individual planets. You can try to modify this part to assign a unique id instead of a cluster id to each planet for your purposes (see how we implement the "clusteridlist" array in "src/model.jl" of SysSimExClusters).

BTW, although "target_id" and "star_id" are both identifiers for the stars in the simulations, they are not the same: "target_id" refers to the index of the star in the simulation (e.g. 1 for the first drawn star, 2 for the second drawn star, etc.) while "star_id" refers to the index of the star based on where it is in the input stellar catalog (i.e. the row number in the "q1_q17_dr25_gaia_fgk_cleaned.csv" catalog, which can be found in the "plotting/" directory). I had updated the README for SysSimExClusters a while ago to make this more clear.

Finally, if you're using the "He_Ford_Ragozzine_2019" branch of SysSimExClusters, then you should be all good (i.e. nothing should have changed), but the master branch has been updated several times (with many things completely overhauled) and is not guaranteed to work at any moment.

Hope this helps and let me know if anything is confusing!

Cheers,
Matthias

**Comment by gjgilbert** [comment]
Matthias,

Thanks for the quick response. Taking the closest period (within a given system) for each observed planet is the approach I landed on, and that appears to be working fine. 

I do recognize that star_id and target_id are different - by redundant I didn't mean to imply that they're identical, simply that for my purposes they encapsulate the same information. I'll look into modifying "cluster id" to create a unique identifier if I need to produce any more catalogues in the future. So to be clear, everything runs well, and all of the outputs make sense.

For now, you've answered my questions and I"m all set!

Thanks again for your help.
